# Use a base image, such as Ubuntu
FROM ubuntu:22.04

WORKDIR /opt/buildDir

# Install pre-requisites
RUN apt-get update -y && \
    apt-get install -y \
    git \
    wget \
    openjdk-19-jre-headless

COPY --chown=root:root docker_script.sh .

CMD ./docker_script.sh $VERSION
